    char* gdriveRsp2 =
    "HTTP/1.1 200 OK\r\n"
    "X-GUploader-UploadID: AEnB2Up2ao2-uhfOFLDeVXUlyehoncRb9TRRmbyDtF5nCEEJsU56Iv1-Y3tu8KMpYBSgc8bAg-YliLWB_P6o2vvMYYbbow7O7w\r\n"
    "ETag: \"fbeGFVkCD3tGFpdjp1CYyuwDABw/MTQ0ODQxOTAyMjk2OA\"\r\n"
    "Vary: Origin\r\n"
    "Vary: X-Origin\r\n"
    "Content-Type: application/json; charset=UTF-8\r\n"
    "Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\n"
    "Pragma: no-cache\r\n"
    "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
    "Date: Wed, 25 Nov 2015 02:37:03 GMT\r\n"
    "Content-Length: 2642\r\n"
    "Server: UploadServer\r\n"
    "Alternate-Protocol: 443:quic,p=1\r\n"
    "Alt-Svc: quic=\":443\"; ma=604800; v=\"30,29,28,27,26,25\"\r\n\r\n"
    "{\n"
    " \"kind\": \"drive#file\",\n"
    " \"id\": \"0BzCkQYBmdM-2SjVfWlFYZ1RtdUU\",\n"
    " \"etag\": \"\\\"fbeGFVkCD3tGFpdjp1CYyuwDABw/MTQ0ODQxOTAyMjk2OA\\\"\",\n"
    " \"selfLink\": \"https://www.googleapis.com/drive/v2/files/0BzCkQYBmdM-2SjVfWlFYZ1RtdUU\",\n"
    " \"webContentLink\": \"https://docs.google.com/uc?id=0BzCkQYBmdM-2SjVfWlFYZ1RtdUU&export=download\",\n"
    " \"alternateLink\": \"https://drive.google.com/file/d/0BzCkQYBmdM-2SjVfWlFYZ1RtdUU/view?usp=drivesdk\",\n"
    " \"iconLink\": \"https://ssl.gstatic.com/docs/doclist/images/generic_app_icon_16.png\",\n"
    " \"title\": \"ca.crt\",\n"
    " \"mimeType\": \"application/x-x509-server-cert\",\n"
    " \"labels\": {\n"
    "  \"starred\": false,\n"
    "  \"hidden\": false,\n"
    "  \"trashed\": false,\n"
    "  \"restricted\": false,\n"
    "  \"viewed\": true\n"
    " },\n"
    " \"createdDate\": \"2015-11-25T02:37:02.968Z\",\n"
    " \"modifiedDate\": \"2015-11-25T02:37:02.968Z\",\n"
    " \"modifiedByMeDate\": \"2015-11-25T02:37:02.968Z\",\n"
    " \"lastViewedByMeDate\": \"2015-11-25T02:37:02.968Z\",\n"
    " \"markedViewedByMeDate\": \"1970-01-01T00:00:00.000Z\",\n"
    " \"version\": \"2881\",\n"
    " \"parents\": [\n"
    "  {\n"
    "   \"kind\": \"drive#parentReference\",\n"
    "   \"id\": \"0ADCkQYBmdM-2Uk9PVA\",\n"
    "   \"selfLink\": \"https://www.googleapis.com/drive/v2/files/0BzCkQYBmdM-2SjVfWlFYZ1RtdUU/parents/0ADCkQYBmdM-2Uk9PVA\",\n"
    "   \"parentLink\": \"https://www.googleapis.com/drive/v2/files/0ADCkQYBmdM-2Uk9PVA\",\n"
    "   \"isRoot\": true\n"
    "  }\n"
    " ],\n"
    " \"downloadUrl\": \"https://doc-0k-3g-docs.googleusercontent.com/docs/securesc/f1j9mtso1c51h24m28j6mu8tk1njqvta/fnggfir5pv5560evn9emhpui6h06ur4d/1448416800000/09500111083742506579/09500111083742506579/0BzCkQYBmdM-2SjVfWlFYZ1RtdUU?e=download&gd=true\",\n"
    " \"userPermission\": {\n"
    "  \"kind\": \"drive#permission\",\n"
    "  \"etag\": \"\\\"fbeGFVkCD3tGFpdjp1CYyuwDABw/aTLaEKfqDjxmIFcmTI0DGsYJ9_M\\\"\",\n"
    "  \"id\": \"me\",\n"
    "  \"selfLink\": \"https://www.googleapis.com/drive/v2/files/0BzCkQYBmdM-2SjVfWlFYZ1RtdUU/permissions/me\",\n"
    "  \"role\": \"owner\",\n"
    "  \"type\": \"user\"\n"
    " },\n"
    " \"originalFilename\": \"ca.crt\",\n"
    " \"fileExtension\": \"crt\",\n"
    " \"md5Checksum\": \"b052b9da9075339cfaa4553e227fc891\",\n"
    " \"fileSize\": \"1919\",\n"
    " \"quotaBytesUsed\": \"1919\",\n"
    " \"ownerNames\": [\n"
    "  \"Test Test\"\n"
    " ],\n"
    " \"owners\": [\n"
    "  {\n"
    "   \"kind\": \"drive#user\",\n"
    "   \"displayName\": \"Test Test\",\n"
    "   \"isAuthenticatedUser\": true,\n"
    "   \"permissionId\": \"09500111083742506579\",\n"
    "   \"emailAddress\": \"andmoslab@gmail.com\"\n"
    "  }\n"
    " ],\n"
    " \"lastModifyingUserName\": \"Test Test\",\n"
    " \"lastModifyingUser\": {\n"
    "  \"kind\": \"drive#user\",\n"
    "  \"displayName\": \"Test Test\",\n"
    "  \"isAuthenticatedUser\": true,\n"
    "  \"permissionId\": \"09500111083742506579\",\n"
    "  \"emailAddress\": \"andmoslab@gmail.com\"\n"
    " },\n"
    " \"editable\": true,\n"
    " \"copyable\": true,\n"
    " \"writersCanShare\": true,\n"
    " \"shared\": false,\n"
    " \"explicitlyTrashed\": false,\n"
    " \"appDataContents\": false,\n"
    " \"headRevisionId\": \"0BzCkQYBmdM-2M2hBbHFmMTF6ZXppRmhEcHhodzB1VmxvenUwPQ\",\n"
    " \"spaces\": [\n"
    "  \"drive\"\n"
    " ]\n"
    "}\r\n\r\n";
